export const ADD_PRODUCT = "ADD_PRODUCT";
export const DATA_LOADED = "DATA_LOADED";
export const DATA_DELETED = "DATA_DELETED";
export const DATA_EDIT = "DATA_EDIT";
export const DATA_UPDATE = "DATA_UPDATE";
export const FETCH_PRODUCT_PENDING = "FETCH_PRODUCT_PENDING";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";

